version: "3.8"
services:
  postgres:
    image: bridge-postgres:latest
    build:
      context: ./docker/postgres
    restart: always
    volumes:
      # Using named volume for db data to allow automatic removal with docker compose down -v
      # This does not work for bind mounts (i.e. volumes that are not managed by docker like initsql)
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/initsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # VERY IMPORTANT: no connections outside localhost
      - 127.0.0.1:65432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge1 -d bridge1 -h postgres"]
      interval: 1s
      timeout: 120s

  bitcoind:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: polarlightning/bitcoind:26.0
    hostname: bitcoind
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-chain=regtest",
        "-rpcuser=polaruser",
        "-rpcpassword=polarpass",
        "getblockchaininfo"
      ]
      interval: 2s
    volumes:
      - ./volumes/bitcoind/bitcoind:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'

  hardhat:
    image:
      bridge_hardhat:latest

    build:
      context: ./bridge_contracts/
      dockerfile: ../docker/hardhat/Dockerfile

    environment:
     - NODE1_ADDRESS=0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
     - NODE2_ADDRESS=0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
     - NODE3_ADDRESS=0xA40013a058E70664367c515246F2560B82552ACb
     - USER_ADDRESS=0xBcd4042DE499D14e55001CcbB24a551F3b954096  # Hardhat Account 10

    ports:
      - 127.0.0.1:18545:8545

  alice-bridge:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - hardhat
      - alice-tap
    ports:
      - 127.0.0.1:8181:8080
    # TODO: needs to be added later, this does not work without pyramid
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:6543/health"]
    #   interval: 120s
    #   timeout: 1s
    volumes:
      - ./volumes/lnd/alice-lnd:/var/bridge/lnd
      - ./volumes/tapd/alice-tap:/var/bridge/tapd
    environment:
      # NOTE: the private keys and other secrets are supposed to be here -- they are not used in the real world, only regtest. Don't report them.
      - BRIDGE_NODE_ID=alice-node
      - BRIDGE_HOSTNAME=alice-bridge
      - BRIDGE_LEADER_NODE_ID=alice-node
      - BRIDGE_DB_URL=postgresql://bridge1:a5f83ab52f2c6c8d0a31e99c@postgres:5432/bridge1
      - LOG_LEVEL=DEBUG
      - BRIDGE_EVM_PRIVATE_KEY=0x9a9a640da1fc0181e43a9ea00b81878f26e1678e3e246b25bd2835783f2be181
      # ^-- address 0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
      - BRIDGE_EVM_BLOCK_SAFETY_MARGIN=1
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=http://hardhat:8545
      - BRIDGE_PEERS=bob-node@bob-bridge:5000
      - BRIDGE_BTC_NETWORK=regtest
      - BRIDGE_BTC_RPC_URL=http://polaruser:polarpass@bitcoind:18443
      # Taproot Assets
      - BRIDGE_TAP_HOST=alice-tap:8089
      - BRIDGE_TAP_MACAROON_PATH=/var/bridge/tapd/data/regtest/admin.macaroon
      - BRIDGE_TAP_TLS_CERT_PATH=/var/bridge/tapd/tls.cert

  bob-bridge:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - alice-bridge
      - bob-tap
    ports:
      - 127.0.0.1:8182:8080
    volumes:
      - ./volumes/lnd/bob-lnd:/var/bridge/lnd
      - ./volumes/tapd/bob-tap:/var/bridge/tapd
    environment:
      # NOTE: the private keys and other secrets are supposed to be here -- they are not used in the real world, only regtest. Don't report them.
      - BRIDGE_NODE_ID=bob-node
      - BRIDGE_HOSTNAME=bob-bridge
      - BRIDGE_LEADER_NODE_ID=alice-node
      - BRIDGE_DB_URL=postgresql://bridge2:b2a8658e648ddc59b5172dfe@postgres:5432/bridge2
      - LOG_LEVEL=DEBUG
      - BRIDGE_EVM_PRIVATE_KEY=0x034262349de8b7bb1d8fdd7a9b6096aae0906a8f3b58ecc31af58b9f9a30e567
      # ^-- address: 0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
      - BRIDGE_EVM_BLOCK_SAFETY_MARGIN=1
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=http://hardhat:8545
      - BRIDGE_PEERS=alice-node@alice-bridge:5000
      - BRIDGE_BTC_NETWORK=regtest
      - BRIDGE_BTC_RPC_URL=http://polaruser:polarpass@bitcoind:18443
      # Taproot Assets
      - BRIDGE_TAP_HOST=bob-tap:8089
      - BRIDGE_TAP_MACAROON_PATH=/var/bridge/tapd/data/regtest/admin.macaroon
      - BRIDGE_TAP_TLS_CERT_PATH=/var/bridge/tapd/tls.cert

  alice-lnd:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/lnd:0.17.3-beta
    hostname: alice-lnd
    depends_on:
      - bitcoind
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice-lnd --externalip=alice-lnd
      --tlsextradomain=alice-lnd --tlsextradomain=alice-lnd
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice-lnd:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10002:10009'
      - '9736:9735'

  bob-lnd:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/lnd:0.17.3-beta
    hostname: bob-lnd
    depends_on:
      - bitcoind
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bob-lnd --externalip=bob-lnd
      --tlsextradomain=bob-lnd --tlsextradomain=bob-lnd
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
    restart: always
    volumes:
      - ./volumes/lnd/bob-lnd:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10003:10009'
      - '9737:9735'

  # TODO: re-enable carol after tests are rewritten for 2-of-3 multisig
#  carol-lnd:
#    environment:
#      USERID: ${USERID:-1000}
#      GROUPID: ${GROUPID:-1000}
#    stop_grace_period: 2m
#    image: polarlightning/lnd:0.17.3-beta
#    hostname: carol-lnd
#    depends_on:
#      - bitcoind
#    command: >-
#      lnd --noseedbackup --trickledelay=5000 --alias=carol-lnd --externalip=carol-lnd
#      --tlsextradomain=carol-lnd --tlsextradomain=carol-lnd
#      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
#      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
#      --bitcoin.regtest --bitcoin.node=bitcoind
#      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=polaruser
#      --bitcoind.rpcpass=polarpass
#      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
#      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
#    restart: always
#    volumes:
#      - ./volumes/lnd/carol-lnd:/home/lnd/.lnd
#    expose:
#      - '8080'
#      - '10009'
#      - '9735'
#    ports:
#      - '8084:8080'
#      - '10004:10009'
#      - '9738:9735'

  user-lnd:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/lnd:0.17.3-beta
    hostname: user-lnd
    depends_on:
      - bitcoind
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=user-lnd --externalip=user-lnd
      --tlsextradomain=user-lnd --tlsextradomain=user-lnd
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
    restart: always
    volumes:
      - ./volumes/lnd/user-lnd:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8085:8080'
      - '10005:10009'
      - '9739:9735'

  alice-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/tapd:0.3.2-alpha
    hostname: alice-tap
    depends_on:
      - alice-lnd
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=alice-tap
      --tlsextradomain=alice-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=alice-lnd:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access
    restart: always
    volumes:
      - ./volumes/lnd/alice-lnd:/home/tap/.lnd
      - ./volumes/tapd/alice-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8289:8089'
      - '12029:10029'
  bob-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/tapd:0.3.2-alpha
    hostname: bob-tap
    depends_on:
      - bob-lnd
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=bob-tap
      --tlsextradomain=bob-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=bob-lnd:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access
    restart: always
    volumes:
      - ./volumes/lnd/bob-lnd:/home/tap/.lnd
      - ./volumes/tapd/bob-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8290:8089'
      - '12030:10029'

  # TODO: re-enable carol after tests are rewritten for 2-of-3 multisig
#  carol-tap:
#    environment:
#      USERID: ${USERID:-1000}
#      GROUPID: ${GROUPID:-1000}
#    stop_grace_period: 2m
#    image: polarlightning/tapd:0.3.2-alpha
#    hostname: carol-tap
#    depends_on:
#      - carol-lnd
#    command: >-
#      tapd --network=regtest --debuglevel=debug --tlsextradomain=carol-tap
#      --tlsextradomain=carol-tap --rpclisten=0.0.0.0:10029
#      --restlisten=0.0.0.0:8089 --lnd.host=carol-lnd:10009
#      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
#      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
#      --allow-public-stats --universe.public-access
#    restart: always
#    volumes:
#      - ./volumes/lnd/carol-lnd:/home/tap/.lnd
#      - ./volumes/tapd/carol-tap:/home/tap/.tapd
#    expose:
#      - '8089'
#      - '10029'
#    ports:
#      - '8291:8089'
#      - '12031:10029'

  user-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: polarlightning/tapd:0.3.2-alpha
    hostname: user-tap
    depends_on:
      - user-lnd
    command: >-
      tapd --network=regtest --debuglevel=debug --tlsextradomain=user-tap
      --tlsextradomain=user-tap --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 --lnd.host=user-lnd:10009
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert --allow-public-uni-proof-courier
      --allow-public-stats --universe.public-access
    restart: always
    volumes:
      - ./volumes/lnd/user-lnd:/home/tap/.lnd
      - ./volumes/tapd/user-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8292:8089'
      - '12032:10029'

  alice-ord:
    image:
      bridge-ord:latest

    build:
      context: ./docker/ord/

    volumes:
      - ./volumes/ord/alice-ord:/home/ord/data

    command: >-
      ord
      --bitcoin-rpc-user polaruser
      --bitcoin-rpc-pass polarpass
      --rpc-url bitcoind:18443
      --chain regtest
      --index-runes
      --data-dir /home/ord/data
      server
      --http
      --http-port 80

    depends_on:
      bitcoind:
        condition: service_healthy

    expose:
      - 80

    ports:
      - 127.0.0.1:3080:80

  user-ord:
    image:
      bridge-ord:latest

    build:
      context: ./docker/ord/

    volumes:
      - ./volumes/ord/user-ord:/home/ord/data

    command: >-
      ord
      --bitcoin-rpc-user polaruser
      --bitcoin-rpc-pass polarpass
      --rpc-url bitcoind:18443
      --chain regtest
      --index-runes
      --data-dir /home/ord/data
      server
      --http
      --http-port 80

    depends_on:
      bitcoind:
        condition: service_healthy

    expose:
      - 80

volumes:
  postgres:
