version: "3.8"
services:
  bitcoin-regtest:
    image:
      sovryn-bitcoind-regtest:latest

    build:
      context: ./local_dev/bitcoind-regtest/

    environment:
     # NOTE: these "secrets" are supposed to be there -- they are not used in the real world. Don't report them.
     - NODE1_HDSEED=cTj4tA23bVHAnA42bYGGPfv13G2dfuChxtenJKsZffkCVMvofcfC
     - NODE2_HDSEED=cUroJKmyKxRJVaeKzprMZExtPoZqt9HPnfhhJvAqtprWCVsuzUBU
     - NODE3_HDSEED=cSsv1YhxQqce8ywLiwhMjKcq9L1J7J2wm66zX7kfB1eLBBBaTt8N
     - USER_HDSEED=cUrw2SDAMapEqZ2pQnh5angJHqzGWvPMPdJNJWTDFagHMcdcciu8
     # sorted !!
     - PUBKEYS=["02f2bfc7a7d86f04d675083c7157d95c5741e85ff69b0c1357059fe1ee52271218","0380d87958cc14e1178f55584ee437b05c155a5a7d9f1951beb927195abaa7a7ed","0397ff0a671bea40a8346d7487810f3a96be95732717e5c568a7c8090a73a6c88b"]
     - MULTISIG_ADDRESS=bcrt1qtxysk2megp39dnpw9va32huk5fesrlvutl0zdpc29asar4hfkrlqs2kzv5
     # replenisher multisig

#rep1.txt:# extended private masterkey: tprv8ZgxMBicQKsPdn254GKf2bYkZkX7qYSTfp1Nd1cZ8mTVsd12ni2K9CmredbD7FY6UvJTfBXG3uJiF24hen5vycv1TUmS9g9MSGLbht9g8FK
#rep2.txt:# extended private masterkey: tprv8ZgxMBicQKsPevFzbHT9BG3m1m7ZtjniHW5UzECpbAPPMUdSisBVVBSJtZzJLWWJ4157NG9wrFqSKbsYBEhj5pWvBuncJANC2EuLi8oRawM

     - 'REPLENISHER_SOURCE_DESCRIPTOR=wsh(sortedmulti(2,tpubD6NzVbkrYhZ4XF3rwuzFS1Cs8n33zsdNF7c9uXerZ3Fti7FoR6quKhPipoXiSY8EXVhwvtCQjFxXMZJKoJNGyuXzaGVQJH6NpjXvo4jdMeQ/0/*,tpubD6NzVbkrYhZ4YPHnUw7jafhsandW44ycrogGGkF81SBnBxtDMG15fg4B4gzdNufXC6PjchXmfY4s2MsS77KDpBGJ8qRxvx4RUfqSzyqcHPq/0/*))#qjj6up2r'
     - REPLENISHER1_XPRV=tprv8ZgxMBicQKsPdn254GKf2bYkZkX7qYSTfp1Nd1cZ8mTVsd12ni2K9CmredbD7FY6UvJTfBXG3uJiF24hen5vycv1TUmS9g9MSGLbht9g8FK
     - REPLENISHER2_XPRV=tprv8ZgxMBicQKsPevFzbHT9BG3m1m7ZtjniHW5UzECpbAPPMUdSisBVVBSJtZzJLWWJ4157NG9wrFqSKbsYBEhj5pWvBuncJANC2EuLi8oRawM
     - REPLENISHER_ADDRESS=bcrt1qh0j5lcsvezdnrljsfcuetwrg7xen4a6ydmx9pt363e27rph2mntslwp447

    ports:
      - 18443:18443

  hardhat:
    image:
      bridge_hardhat:latest

    build:
      context: ./bridge_contracts/
      dockerfile: ../local_dev/hardhat/Dockerfile

    environment:
     - NODE1_ADDRESS=0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
     - NODE2_ADDRESS=0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
     - NODE3_ADDRESS=0xA40013a058E70664367c515246F2560B82552ACb
     - USER_ADDRESS=0xB3b77A8Bc6b6fD93D591C0F34f202eC02e9af2e8

    ports:
      - 18545:8545


  bridge-node-1:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
    # TODO: needs to be added later, this does not work without pyramid
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:6543/health"]
    #   interval: 120s
    #   timeout: 1s
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-1
      - LOG_LEVEL=DEBUG

  bridge-node-2:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - bridge-node-1
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-2
      - LOG_LEVEL=DEBUG

  bridge-node-3:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - bridge-node-2
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-3
      - LOG_LEVEL=DEBUG

  postgres:
    image: bridge-postgres:latest
    build:
      context: ./docker/postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./docker/postgres/initsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # VERY IMPORTANT: no connections outside localhost
      - 127.0.0.1:65432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge -d bridge -h postgres"]
      interval: 1s
      timeout: 120s

volumes:
  db_data:
