version: "3.8"
services:
  bitcoin-regtest:
    image:
      sovryn-bitcoind-regtest:latest

    build:
      context: ./local_dev/bitcoind-regtest/

    environment:
     # NOTE: these "secrets" are supposed to be there -- they are not used in the real world. Don't report them.
     - NODE1_HDSEED=cTj4tA23bVHAnA42bYGGPfv13G2dfuChxtenJKsZffkCVMvofcfC
     - NODE2_HDSEED=cUroJKmyKxRJVaeKzprMZExtPoZqt9HPnfhhJvAqtprWCVsuzUBU
     - NODE3_HDSEED=cSsv1YhxQqce8ywLiwhMjKcq9L1J7J2wm66zX7kfB1eLBBBaTt8N
     - USER_HDSEED=cUrw2SDAMapEqZ2pQnh5angJHqzGWvPMPdJNJWTDFagHMcdcciu8
     # sorted !!
     - PUBKEYS=["02f2bfc7a7d86f04d675083c7157d95c5741e85ff69b0c1357059fe1ee52271218","0380d87958cc14e1178f55584ee437b05c155a5a7d9f1951beb927195abaa7a7ed","0397ff0a671bea40a8346d7487810f3a96be95732717e5c568a7c8090a73a6c88b"]
     - MULTISIG_ADDRESS=bcrt1qtxysk2megp39dnpw9va32huk5fesrlvutl0zdpc29asar4hfkrlqs2kzv5

    ports:
      - 127.0.0.1:18443:18443

  hardhat:
    image:
      bridge_hardhat:latest

    build:
      context: ./bridge_contracts/
      dockerfile: ../local_dev/hardhat/Dockerfile

    environment:
     - NODE1_ADDRESS=0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
     - NODE2_ADDRESS=0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
     - NODE3_ADDRESS=0xA40013a058E70664367c515246F2560B82552ACb
     - USER_ADDRESS=0xBcd4042DE499D14e55001CcbB24a551F3b954096  # Hardhat Account 10

    ports:
      - 127.0.0.1:18545:8545


  bridge-node-1:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./bridge_node/certs/bridge-node-1-client-cert.pem:/certs/client-cert.pem:ro
      - ./bridge_node/certs/bridge-node-1-client-key.pem:/certs/client-key.pem:ro
      - ./bridge_node/certs/bridge-node-1-server-cert.pem:/certs/server-cert.pem:ro
      - ./bridge_node/certs/bridge-node-1-server-key.pem:/certs/server-key.pem:ro
      - ./bridge_node/certs/ca-cert.pem:/certs/ca-cert.pem:ro
    # TODO: needs to be added later, this does not work without pyramid
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:6543/health"]
    #   interval: 120s
    #   timeout: 1s
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-1
      - BRIDGE_HOSTNAME=bridge-node-1
      - LOG_LEVEL=DEBUG
      - BRIDGE_EVM_PRIVATE_KEY=0x9a9a640da1fc0181e43a9ea00b81878f26e1678e3e246b25bd2835783f2be181
      # ^-- address 0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=http://hardhat:8545
      - BRIDGE_PEERS=rollup-bridge-2@bridge-node-2:5000,rollup-bridge-3@bridge-node-3:5000
      - BRIDGE_BTC_NETWORK=regtest
      - BRIDGE_BTC_RPC_URL=http://bridgebtc:hunter3@bitcoin-regtest:18443/wallet/multisig
      #- BRIDGE_BTC_MASTER_PRIVATE_KEY=tprv8ZgxMBicQKsPdLiVtqrvinq5JyvByQZs4xWMgzZ3YWK7ndu27yQ3qoWivh8cgdtB3bKuYKWRKhaEvtykaFCsDCB7akNdcArjgrCnFhuDjmV
      #- BRIDGE_BTC_MASTER_PUBLIC_KEYS=tpubD6NzVbkrYhZ4WokHnVXX8CVBt1S88jkmeG78yWbLxn7Wd89nkNDe2J8b6opP4K38mRwXf9d9VVN5uA58epPKjj584R1rnDDbk6oHUD1MoWD,tpubD6NzVbkrYhZ4WpZfRZip3ALqLpXhHUbe6UyG8iiTzVDuvNUyysyiUJWejtbszZYrDaUM8UZpjLmHyvtV7r1QQNFmTqciAz1fYSYkw28Ux6y,tpubD6NzVbkrYhZ4WQZnWqU8ieBsujhoZKZLF6wMvTApJ4ZiGmipk481DyM2su3y5BDeB9fFLwSmmmsGDGJum79he2fnuQMnpWhe3bGir7Mf4uS

  bridge-node-2:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - bridge-node-1
    volumes:
      - ./bridge_node/certs/bridge-node-2-client-cert.pem:/certs/client-cert.pem:ro
      - ./bridge_node/certs/bridge-node-2-client-key.pem:/certs/client-key.pem:ro
      - ./bridge_node/certs/bridge-node-2-server-cert.pem:/certs/server-cert.pem:ro
      - ./bridge_node/certs/bridge-node-2-server-key.pem:/certs/server-key.pem:ro
      - ./bridge_node/certs/ca-cert.pem:/certs/ca-cert.pem:ro
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-2
      - BRIDGE_HOSTNAME=bridge-node-2
      - LOG_LEVEL=DEBUG
      - BRIDGE_EVM_PRIVATE_KEY=0x034262349de8b7bb1d8fdd7a9b6096aae0906a8f3b58ecc31af58b9f9a30e567
      # ^-- address: 0x09dcD91DF9300a81a4b9C85FDd04345C3De58F48
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=http://hardhat:8545
      - BRIDGE_PEERS=rollup-bridge-1@bridge-node-1:5000,rollup-bridge-3@bridge-node-3:5000
      - BRIDGE_BTC_NETWORK=regtest
      - BRIDGE_BTC_RPC_URL=http://bridgebtc:hunter3@bitcoin-regtest:18443/wallet/multisig
      #- BRIDGE_BTC_MASTER_PRIVATE_KEY=tprv8ZgxMBicQKsPdMXsXv4Ddkgimo1m89QjXBNUrCgAaDRX5tEDMVA8HotnZmHcMvUVtgh1yXbN74StoJqv76jvRxJmkr2wvkPwTbZb1zeXv3Y
      #- BRIDGE_BTC_MASTER_PUBLIC_KEYS=tpubD6NzVbkrYhZ4WokHnVXX8CVBt1S88jkmeG78yWbLxn7Wd89nkNDe2J8b6opP4K38mRwXf9d9VVN5uA58epPKjj584R1rnDDbk6oHUD1MoWD,tpubD6NzVbkrYhZ4WpZfRZip3ALqLpXhHUbe6UyG8iiTzVDuvNUyysyiUJWejtbszZYrDaUM8UZpjLmHyvtV7r1QQNFmTqciAz1fYSYkw28Ux6y,tpubD6NzVbkrYhZ4WQZnWqU8ieBsujhoZKZLF6wMvTApJ4ZiGmipk481DyM2su3y5BDeB9fFLwSmmmsGDGJum79he2fnuQMnpWhe3bGir7Mf4uS

  bridge-node-3:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
      - bridge-node-2
    volumes:
      - ./bridge_node/certs/bridge-node-3-client-cert.pem:/certs/client-cert.pem:ro
      - ./bridge_node/certs/bridge-node-3-client-key.pem:/certs/client-key.pem:ro
      - ./bridge_node/certs/bridge-node-3-server-cert.pem:/certs/server-cert.pem:ro
      - ./bridge_node/certs/bridge-node-3-server-key.pem:/certs/server-key.pem:ro
      - ./bridge_node/certs/ca-cert.pem:/certs/ca-cert.pem:ro
    environment:
      - BRIDGE_NODE_ID=rollup-bridge-3
      - BRIDGE_HOSTNAME=bridge-node-3
      - LOG_LEVEL=DEBUG
      - BRIDGE_EVM_PRIVATE_KEY=0xbce34f7111bb4a3174f90b34f327b5a92788a19bbda6b73aa4b945e149c06ba8
      # ^-- address: 0xA40013a058E70664367c515246F2560B82552ACb
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=http://hardhat:8545
      - BRIDGE_PEERS=rollup-bridge-1@bridge-node-1:5000,rollup-bridge-2@bridge-node-2:5000
      - BRIDGE_BTC_NETWORK=regtest
      - BRIDGE_BTC_RPC_URL=http://bridgebtc:hunter3@bitcoin-regtest:18443/wallet/multisig
      #- BRIDGE_BTC_MASTER_PRIVATE_KEY=tprv8ZgxMBicQKsPcwXzdBoYKEXmLiBsPzNRfoLadw8WsnmKSHU47fJR3UjAhni8kt5bx5jFG9JZ4oZuxnaX6beTNwc2C5coMHmAvnKpqHA8xVb
      #- BRIDGE_BTC_MASTER_PUBLIC_KEYS=tpubD6NzVbkrYhZ4WokHnVXX8CVBt1S88jkmeG78yWbLxn7Wd89nkNDe2J8b6opP4K38mRwXf9d9VVN5uA58epPKjj584R1rnDDbk6oHUD1MoWD,tpubD6NzVbkrYhZ4WpZfRZip3ALqLpXhHUbe6UyG8iiTzVDuvNUyysyiUJWejtbszZYrDaUM8UZpjLmHyvtV7r1QQNFmTqciAz1fYSYkw28Ux6y,tpubD6NzVbkrYhZ4WQZnWqU8ieBsujhoZKZLF6wMvTApJ4ZiGmipk481DyM2su3y5BDeB9fFLwSmmmsGDGJum79he2fnuQMnpWhe3bGir7Mf4uS

  postgres:
    image: bridge-postgres:latest
    build:
      context: ./docker/postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./docker/postgres/initsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # VERY IMPORTANT: no connections outside localhost
      - 127.0.0.1:65432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge -d bridge -h postgres"]
      interval: 1s
      timeout: 120s

volumes:
  db_data:
