version: "3.8"
name: sovryn-nbte-bridge
services:
  postgres:
    image: bridge-postgres:latest
    build:
      context: ./docker/postgres
    restart: always
    volumes:
      # Using named volume for db data to allow automatic removal with docker compose down -v
      # This does not work for bind mounts (i.e. volumes that are not managed by docker like initsql)
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./docker/postgres/initsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # VERY IMPORTANT: no connections outside localhost
      - 127.0.0.1:65432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge1 -d bridge1 -h postgres"]
      interval: 1s
      timeout: 120s

  bitcoind:
    image:
      sovryn-runes-bitcoind:latest

    build:
      context: ./docker/bitcoind/

    volumes:
      - ./volumes/bitcoind:/home/bitcoin/.bitcoin

    command: >-
      bitcoind
      -server=1
      -testnet
      -rpcuser=bitcoinuser -rpcpassword=bitcoinpass
      -debug=1 -printtoconsole
      -listenonion=0
      -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18332 -port=18333
      -txindex=1

    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-testnet",
        "-rpcport=18332",
        "-rpcuser=bitcoinuser",
        "-rpcpassword=bitcoinpass",
        "getblockchaininfo"
      ]
      interval: 5s

    expose:
      - 18333
      - 18332

    ports:
      - 127.0.0.1:18333:18333
      - 127.0.0.1:18332:18332

  ord:
    image:
      bridge-ord:latest

    build:
      context: ./docker/ord/

    volumes:
      - ./volumes/ord:/home/ord/data

    command: >-
      ord
      --bitcoin-rpc-username bitcoinuser
      --bitcoin-rpc-password bitcoinpass
      --bitcoin-rpc-url bitcoind:18332
      --chain testnet
      --index-runes
      --data-dir /home/ord/data
      server
      --http
      --http-port 80
      --polling-interval 5s

    depends_on:
      bitcoind:
        condition: service_healthy

    expose:
      - 80

    ports:
      - 127.0.0.1:3080:80

  bridge-node-1:
    image: bridge_node:latest
    build:
      context: bridge_node
    restart: always
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:8181:8080
    environment:
      # NOTE: the private keys and other secrets are supposed to be here -- they are not used in the real world, only regtest. Don't report them.
      - BRIDGE_NODE_ID=node-1
      - BRIDGE_HOSTNAME=bridge-node-1
      - BRIDGE_LEADER_NODE_ID=node-1
      - BRIDGE_DB_URL=postgresql://bridge1:a5f83ab52f2c6c8d0a31e99c@postgres:5432/bridge1
      - LOG_LEVEL=DEBUG
      - BRIDGE_ENABLED_BRIDGES=runesrsk
      - BRIDGE_EVM_PRIVATE_KEY=0x9a9a640da1fc0181e43a9ea00b81878f26e1678e3e246b25bd2835783f2be181
      # ^-- address 0x4091663B0a7a14e35Ff1d6d9d0593cE15cE7710a
      - BRIDGE_EVM_BLOCK_SAFETY_MARGIN=1
      - BRIDGE_EVM_BRIDGE_CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
      - BRIDGE_EVM_RPC_URL=https://testnet.sovryn.app/rpc
      - BRIDGE_PEERS=
      - BRIDGE_BTC_NETWORK=testnet
      - BRIDGE_BTC_RPC_URL=http://bitcoinuser:bitcoinpass@bitcoind:18332
      # Taproot Assets
      - BRIDGE_TAP_HOST=
      - BRIDGE_TAP_MACAROON_PATH=
      - BRIDGE_TAP_TLS_CERT_PATH=
      # RUNES
      # TODO: we use the same keys as tap bridge. Might cause problems or not.
      # RUNES COMMON
      - BRIDGE_RUNES_RUNE_BRIDGE_CONTRACT_ADDRESS=0x09E4D1C764113AbeE5986d5CF7A53893491a4BA8
      - BRIDGE_RUNES_EVM_DEFAULT_START_BLOCK=4943737
      - BRIDGE_RUNES_ORD_API_URL=http://ord:80
      - BRIDGE_RUNES_EVM_RPC_URL=https://testnet.sovryn.app/rpc
      - BRIDGE_SECRET_RUNES_BTC_MASTER_XPUBS=${BRIDGE_SECRET_RUNES_BTC_MASTER_XPUBS}
      # RUNES NODE-SPECIFIC
      - BRIDGE_RUNES_BTC_RPC_WALLET_URL=http://bitcoinuser:bitcoinpass@bitcoind:18332/wallet/runebridge
      - BRIDGE_SECRET_RUNES_EVM_PRIVATE_KEY=${BRIDGE_SECRET_RUNES_EVM_PRIVATE_KEY}
      - BRIDGE_SECRET_RUNES_BTC_MASTER_XPRIV=${BRIDGE_SECRET_RUNES_BTC_MASTER_XPRIV}
