"""initialize the SovrynNBTEBridge database, adding the example model

Revision ID: INIT
Revises:
Create Date: 2017-08-28 21:28:19.349054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "INIT"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
    )
    op.create_index("my_index", "models", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("my_index", table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
