"""sender-rsk-address

Revision ID: a7e13c40a244
Revises: 2fa523364d25
Create Date: 2024-02-17 23:57:39.873500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e13c40a244'
down_revision = '2fa523364d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taprsk_rsk_to_tap_transfer', sa.Column('sender_rsk_address', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taprsk_rsk_to_tap_transfer', 'sender_rsk_address')
    # ### end Alembic commands ###
