"""runebridgestuff

Revision ID: deb62cf78dee
Revises: a7e13c40a244
Create Date: 2024-04-03 10:04:57.696308

"""
from alembic import op
import sqlalchemy as sa


revision = 'deb62cf78dee'
down_revision = 'a7e13c40a244'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('runes_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bridge_id', sa.Text(), nullable=False),
    sa.Column('evm_address', sa.LargeBinary, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runes_user')),
    sa.UniqueConstraint('bridge_id', 'evm_address', name='uq_runes_user_evm_address')
    )
    op.create_table('runes_deposit_address',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('btc_address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['runes_user.id'], name=op.f('fk_runes_deposit_address_user_id_runes_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_runes_deposit_address')),
    sa.UniqueConstraint('btc_address', name=op.f('uq_runes_deposit_address_btc_address'))
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runes_deposit_address')
    op.drop_table('runes_user')
    # ### end Alembic commands ###
